### ISSUE TITLE
Adjust frequency of polling

### ISSUE THREAD

**Issue by jeffehobbs** [robmarkcole/HASS-Google-Coral#3]
I'm having an "overheating" issue with my Coral TPU. It would be useful (for the sake of troubleshooting) to be able to adjust the polling somewhere less than 10 seconds. Where would it be best to adjust that?

**Comment by lmamakos** [comment]
You can use the `scan_interval:` specification.  This is a generic sort of home assistant thing, the documentation not immediately obvious.  https://www.home-assistant.io/docs/configuration/platform_options/  and https://www.home-assistant.io/components/image_processing/ mention this, if only you knew to search for `scan_interval` to find those pages :-)

**Comment by jeffehobbs** [comment]
Thank you very much, this is exactly what I needed. Thanks again!
