### ISSUE TITLE
Pass along inference image with bounding box to HASS

### ISSUE THREAD

**Issue by thepiam** [robmarkcole/HASS-Google-Coral#5]
I’ve been using this and it works great - thank you so much!
Total noob question - would it be possible to pass along  inference images with bounding boxes to home assistant to integrate with notifications, similar to what is shown in the example jupyter notebook in this repo?
Thanks so much again.

**Comment by robmarkcole** [comment]
Created an issue on the downstream repo https://github.com/robmarkcole/coral-pi-rest-server/issues/14
